name: CI

on: [push]

jobs:
  build:
    env:
      API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest

    steps:
    - uses: subosito/flutter-action@v1
    - uses: actions/checkout@v1
    - run: flutter channel master
    - run: flutter upgrade
    - run: flutter pub get
    - run: flutter pub run build_runner build --delete-conflicting-outputs 
    - run: flutter test
    - run: flutter build apk
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
